title: Saeed Al Neyadi
tagline: Software Engineer & AI Enthusiast
url: "https://saeed-alneyadi.github.io"
baseurl: ""  # this stays empty for GitHub Pages
lang: en

author:
  name: Saeed Al Neyadi
  url: https://linkedin.com/in/yourprofile

theme_mode: auto  # enables dark/light switch

nav:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: CV
    url: /cv/
