# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Saeed Khaled Alneyadi
title: Computer Science and Engineering Graduate
email: saeed-alneyadi@outlook.com
website: https://github.com/Saeed-Alneyadi

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: uaefalcon_7
github_username:  saeed-alneyadi
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: s.uxr
linkedin_username: saeed-alneyadi-b87482247
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Saeed, a Computer Science and Engineering graduate from The Ohio State University with a strong interest in Artificial Intelligence, Cybersecurity, and Data Analytics. I’ve completed two internships and worked on several projects, including a recipe recommendation web app using Flask, Docker, and Elasticsearch, as well as an algorithmic trading system integrating Alpaca API and sentiment analysis. I'm passionate about building intelligent and secure systems, continuously expanding my portfolio, and preparing for AI and cybersecurity competitions. When I’m not coding, you’ll likely find me jogging or taking on push-up challenges.

  I am most skilled in: <mark>Python</mark> and <mark>Coding</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/saeed-alneyadi
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/saeed-alneyadi
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest projects ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Halo Investing
        link: https://haloinvesting.com/
        # link_text: boringcompany.com
        sub_title: Software Engineering Intern
        caption: June 2023 - July 2023
        quote: >
          Halo Investing is an award‑winning financial technology marketplace that democratizes access to protective investment solutions like structured notes, buffered ETFs, and annuities. Its platform connects financial advisors and institutions with global banks and insurers, enabling streamlined investment workflows and personalized portfolio construction.
        description: | # this will include new lines to allow paragraphs
            During my internship at Halo Investing, I worked closely with engineers and product team members to support the growth of their structured products marketplace. I contributed to tasks involving data integration, backend services development, and automation of investment workflows. Through agile project cycles, I enhanced my understanding of FinTech systems and financial instruments, and gained experience collaborating on meaningful features for advisors and investors using cloud-based tools and Python-based services.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Ohio State University
        caption: January 2021 - August 2024
        sub_title: BSc Computer Science
        quote: >
          Founded in 1870, The Ohio State University is one of the largest and most respected public research universities in the United States, known for its academic excellence, innovation, and global impact across science, engineering, and technology.
        description: | # this will include new lines to allow paragraphs
          During my time at Ohio State, I developed a strong foundation in computer science and engineering, gaining both theoretical knowledge and hands-on experience through internships and real-world projects. My coursework and personal initiatives strengthened my skills in areas like artificial intelligence, cybersecurity, and data analytics. I particularly enjoyed working on a recipe recommendation web app using Flask, Docker, and Elasticsearch, and experimenting with trading bots and sentiment analysis. Beyond academics, I focused on maintaining a balance between performance, creativity, and self-discipline—skills I carry forward into every project and challenge I take on.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Swimming
      - Gaming
      - Football

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
